services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    restart: always
    env_file: 
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file: 
      - .env
    expose:
      - "9000"
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: 
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception

  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis
    restart: always
    env_file: 
      - .env
    ports:
      - "6379:6379"
    networks:
      - inception

  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception

  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer
    restart: always
    env_file: 
      - .env
    expose:
      - "8080:8080"
    networks:
      - inception

  static:
    container_name: static
    image: static
    build: ./requirements/bonus/static
    restart: always
    env_file: 
      - .env
    volumes:
      - ./requirements/bonus/static/content:/usr/share/nginx/html
    ports:
      - "8443:8443"
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build: ./requirements/bonus/cadvisor
    restart: always
    env_file: 
      - .env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - "6000:6000"
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/nzhuzhle/data/wordpress"
      o: bind
      type: none

  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/nzhuzhle/data/mariadb"
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge
