- name: Install and configure Docker with Docker Compose
  hosts: myhosts
  become: true

  tasks:
    - name: Create application directory
      file:
        path: /home/{{ ansible_user }}/app
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: /home/{{ ansible_user }}/app/docker-compose.yml
        dest: /home/{{ ansible_user }}/app/docker-compose.yml
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy .env file
      copy:
        src: /home/{{ ansible_user }}/app/.env
        dest: /home/{{ ansible_user }}/app/.env
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy image file
      copy:
        src: /home/{{ ansible_user }}/app/cloud.jpg
        dest: /home/{{ ansible_user }}/app/cloud.jpg
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy wp-install.sh script
      copy:
        src: /home/{{ ansible_user }}/app/wp-install.sh
        dest: /home/{{ ansible_user }}/app/wp-install.sh
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy nginx.conf file
      copy:
        src: /home/{{ ansible_user }}/app/nginx.conf
        dest: /home/{{ ansible_user }}/app/nginx.conf
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Obtain SSL certificates with Certbot (standalone)
      shell: |
        docker run --rm -p 80:80 \
          -v $PWD/certbot/conf:/etc/letsencrypt \
          -v $PWD/certbot/www:/var/www/certbot \
          certbot/certbot certonly --standalone \
          --non-interactive --agree-tos --email admin@email.com \
          -d mrlouf.studio -d www.mrlouf.studio
      args:
        chdir: /home/{{ ansible_user }}/app

    - name: Start Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/app
        state: present