- name: Install and configure Docker with Docker Compose
  hosts: myhosts
  become: true

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/{{ ansible_user }}/app/docker-compose.yml
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy .env file
      copy:
        src: .env
        dest: /home/{{ ansible_user }}/app/.env
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy image file
      copy:
        src: cloud.jpg
        dest: /home/{{ ansible_user }}/app/cloud.jpg
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy wp-install.sh script
      copy:
        src: wp-install.sh
        dest: /home/{{ ansible_user }}/app/wp-install.sh
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy nginx.conf file
      copy:
        src: nginx.conf
        dest: /home/{{ ansible_user }}/app/nginx.conf
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Start Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/app
        state: present
