- name: Stop Docker Compose stack and cleans up
  become: true
  roles:
    - stop

  tasks:
    - name: Stop Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/app
        state: absent

    - name: Remove unused Docker images
      shell: docker system prune -af

    - name: Remove unused Docker volumes
      shell: docker system prune --volumes -f

    - name: Remove application files
      file:
        path: /home/{{ ansible_user }}/app
        state: absent